# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(392, 420)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("""
        QWidget {
            background-color: #FAFAFA;
        }
        """)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 391, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")

        self.VerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.VerticalLayout.setObjectName("VerticalLayout")

        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")

        self.Main_Page = QtWidgets.QWidget()
        self.Main_Page.setObjectName("Main_Page")

        self.TimerButton = QtWidgets.QPushButton(self.Main_Page)
        self.TimerButton.setGeometry(QtCore.QRect(130, 320, 131, 51))
        self.TimerButton.setObjectName("TimerButton")

        self.stackedWidget.addWidget(self.Main_Page)

        self.Settings_Page = QtWidgets.QWidget()
        self.Settings_Page.setObjectName("Settings_Page")

        self.WorkTimeSlider = QtWidgets.QSlider(self.Settings_Page)
        self.WorkTimeSlider.setGeometry(QtCore.QRect(40, 60, 311, 22))
        self.WorkTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.WorkTimeSlider.setObjectName("WorkTimeSlider")

        self.ShortBreakSlider = QtWidgets.QSlider(self.Settings_Page)
        self.ShortBreakSlider.setGeometry(QtCore.QRect(40, 120, 311, 22))
        self.ShortBreakSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ShortBreakSlider.setObjectName("ShortBreakSlider")

        self.LongBreakSlider = QtWidgets.QSlider(self.Settings_Page)
        self.LongBreakSlider.setGeometry(QtCore.QRect(40, 180, 311, 22))
        self.LongBreakSlider.setOrientation(QtCore.Qt.Horizontal)
        self.LongBreakSlider.setObjectName("LongBreakSlider")

        self.CyclesSlider = QtWidgets.QSlider(self.Settings_Page)
        self.CyclesSlider.setGeometry(QtCore.QRect(40, 240, 311, 22))
        self.CyclesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CyclesSlider.setObjectName("CyclesSlider")

        self.WorkTimeLabel = QtWidgets.QLabel(self.Settings_Page)
        self.WorkTimeLabel.setGeometry(QtCore.QRect(40, 30, 200, 16))
        self.WorkTimeLabel.setObjectName("WorkTimeLabel")

        self.ShortBreakLabel = QtWidgets.QLabel(self.Settings_Page)
        self.ShortBreakLabel.setGeometry(QtCore.QRect(40, 90, 200, 16))
        self.ShortBreakLabel.setObjectName("ShortBreakLabel")

        self.LongBreakLabel = QtWidgets.QLabel(self.Settings_Page)
        self.LongBreakLabel.setGeometry(QtCore.QRect(40, 150, 200, 16))
        self.LongBreakLabel.setObjectName("LongBreakLabel")

        self.CyclesLabel = QtWidgets.QLabel(self.Settings_Page)
        self.CyclesLabel.setGeometry(QtCore.QRect(40, 210, 200, 16))
        self.CyclesLabel.setObjectName("CyclesLabel")

        self.ApplyButton = QtWidgets.QPushButton(self.Settings_Page)
        self.ApplyButton.setGeometry(QtCore.QRect(130, 300, 131, 51))
        self.ApplyButton.setObjectName("ApplyButton")

        self.stackedWidget.addWidget(self.Settings_Page)
        self.VerticalLayout.addWidget(self.stackedWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 21))
        self.menubar.setObjectName("menubar")

        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")

        self.menuThemes = QtWidgets.QMenu(self.menuSettings)
        self.menuThemes.setObjectName("menuThemes")

        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        MainWindow.setMenuBar(self.menubar)

        self.actionThemes = QtWidgets.QAction(MainWindow)
        self.actionThemes.setObjectName("actionThemes")

        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")

        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")

        self.menuThemes.addAction(self.actionLight)
        self.menuThemes.addAction(self.actionDark)
        self.menuSettings.addAction(self.actionThemes)
        self.menuSettings.addAction(self.menuThemes.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        button_style = """
        QPushButton {
            background-color: #C63636;
            color: #FFFFFF;
            border: none;
            border-radius: 14px;
            padding-top: 8px;
            padding-bottom: 12px;
            padding-left: 26px;
            padding-right: 26px;
            font-size: 20px;
            font-weight: 500;
            font-family: 'Inter', 'Segoe UI', system-ui, sans-serif;
        }
        QPushButton:hover {
            background-color: #D64545;
        }
        QPushButton:pressed {
            background-color: #A92B2B;
        }
        """
        self.TimerButton.setStyleSheet(button_style)
        self.ApplyButton.setStyleSheet(button_style)

        label_style = """
        QLabel {
            color: #2E2E2E;
            font-size: 13px;
            font-weight: 500;
        }
        """
        self.WorkTimeLabel.setStyleSheet(label_style)
        self.ShortBreakLabel.setStyleSheet(label_style)
        self.LongBreakLabel.setStyleSheet(label_style)
        self.CyclesLabel.setStyleSheet(label_style)

        self.CloseButton = QtWidgets.QPushButton("✕", self.centralwidget)
        self.CloseButton.setGeometry(350, 10, 32, 32)
        self.CloseButton.setStyleSheet("""
        QPushButton {
            background: transparent;
            border: none;
            font-size: 18px;
        }
        QPushButton:hover {
            color: #C63636;
        }
        """)
        self.CloseButton.clicked.connect(MainWindow.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pomodoro Timer"))
        self.Main_Page.setWhatsThis(_translate(
            "MainWindow",
            "<html><head/><body><p>This is page with Pomodoro timer.</p></body></html>"
        ))
        self.TimerButton.setText(_translate("MainWindow", "Start"))
        self.WorkTimeLabel.setText(_translate("MainWindow", "Work Time"))
        self.ShortBreakLabel.setText(_translate("MainWindow", "Short Break"))
        self.LongBreakLabel.setText(_translate("MainWindow", "Long Break"))
        self.CyclesLabel.setText(_translate("MainWindow", "Cycles"))
        self.ApplyButton.setText(_translate("MainWindow", "Apply"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuThemes.setTitle(_translate("MainWindow", "Themes"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionThemes.setText(_translate("MainWindow", "Set Timer..."))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))